### ISSUE TITLE
Unleash jenkins plugin in multibranch project

### ISSUE THREAD

**Issue by frank-montyne** [shillner/unleash-maven-plugin#103]
Is there a possibility to use the unleash Jenkins plugin in  multibranch projects? If not, could it be possible at all and be considered as an enhancement request?

Thanks,
Frank

**Comment by shillner** [comment]
I assume you mean the multibranch pipeline stuff.
This is currently not possible and is even not clear to me how to integrate unleash as a plugin into such a setup reusing the configured maven stuff. There are many open questions with the pipeline model (free configuration of maven calls, no badge icons, no actions, ...).

It could be considered but I fear that this would require either too much effort or it isn't possible at all.

**Comment by pfink** [comment]
For what do you need the Jenkins plugin? You can just use the `withMaven` and `sh` steps within the pipeline and you're fine.

**Comment by shillner** [comment]
Yes sure, you can do this.
This works but you won't have badge icons or a button to push on for starting a release. You'll likely have to set up a separate job for that.  Montag, 14 Mai 2018, 09:19nachm. +02:00 von Patrick Fink  notifications@github.com :

**Comment by frank-montyne** [comment]
Yes exactly,

I was hoping not to have to setup another 60 Jenkins projects. Maybe I can
do some conditional branching in the groovy pipeline using environment
variables to keep builds and releases in the same Jenkins project.

Thanks anyway!

**Comment by shillner** [comment]
Please let me know if there are some suitable setups or ideas of how you can work with the pipeline stuff.

**Comment by frank-montyne** [comment]
Sure!

**Comment by shillner** [comment]
Closing this issue as this is related to the jenkins plugin.
It is currently not planned to investigate the pipeline support of the Jenkins plugin.
