### ISSUE TITLE
Possibly incorrect information in logs and metadata

### ISSUE THREAD

**Issue by alevinetx** [shillner/unleash-maven-plugin#104]
Unless I'm not understanding what these values should reflect, I think there are some errors in the logs and the generated releaseMetadata.properties:

Jenkins Log:
```
Checking out Revision e8fe12f73a136ba5be3cffca124face59eee0da4 
...
Stored SCM revision before project release: e8fe12f73a136ba5be3cffca124face59eee0da4
...
Checking remote SCM repository for changes. Initial revision was e8fe12f73a136ba5be3cffca124face59eee0da4
Tagging local and remote SCM repositories.
Git - Searching for Git tag '1.3.4'
Git - Tagging local repository with '1.3.4'
Git - Committing local changes.
Git - Commit finished successfully. New revision is: 39bf2bfbc61782ab964ff792900f688aa1d8cfb0
Git - Tag creation finished successfully. New revision is: e8fe12f73a136ba5be3cffca124face59eee0da4
Preparing project modules for next development cycle.
Git - Committing local changes.
Git - Pushing local changes to remote repository.
Git - Updating local repository with remote changes.
Git - Update finished successfully. New revision is: 3ef1f1d307a8188954715660dd831a25506ed6b0
```
releaseMetadata..properties
```
#The unleash release metadata
#Tue Jun 26 11:45:53 CDT 2018
scm.rev.afterTag=e8fe12f73a136ba5be3cffca124face59eee0da4
scm.rev.beforeTag=
scm.tag.name=1.3.4
release.deploymentRepository.id=deployment
version.reactor.post.release=1.3.5-SNAPSHOT
scm.rev.beforeNextDev=e8fe12f73a136ba5be3cffca124face59eee0da4
scm.rev.initial=e8fe12f73a136ba5be3cffca124face59eee0da4
version.reactor.pre.release=1.3.4-SNAPSHOT
scm.tag.namePattern=@{project.version}
release.deploymentRepository.url=**obscured for posting**
version.reactor.release=1.3.4
scm.rev.afterNextDev=3ef1f1d307a8188954715660dd831a25506ed6b0
```

Verified in git:
1.3.4: 39bf2bfbc61....

And, if it matters, my workflow
```
storeScmRevision
checkProjectVersions
checkParentVersions
checkDependencies
checkPlugins
checkPluginDependencies
prepareVersions
checkAether
setReleaseVersions
addSpyPlugin
# buildReleaseArtifacts
removeSpyPlugin
checkForScmChanges
tagScm
# detectReleaseArtifacts
setDevVersion
# -- doesn't exist in default workflow, must add cdi plugins : 
serializeMetadata
# installArtifacts
# deployArtifacts
```

Thank you for your continued work on this!

**Comment by alevinetx** [comment]
I realize the ``detectReleaseArtifacts`` is commented out, but I'm not building any artifacts at this step.  And with it uncommented, I get a stack trace:

```
[INFO] 12:06:33,167  Detecting all release artifacts that have been produced during the release build for later installation and deployment.
[ERROR] An exception was caught while processing the workflow step with id 'detectReleaseArtifacts'.
org.apache.maven.plugin.MojoFailureException: Could not find artifact-spy output file containing all project artifacts. File was expected at /home/jenkins/workspace/Adam/Prepare for PR/target/artifact-spy/artifacts.properties
	at com.itemis.maven.plugins.unleash.steps.actions.DetectReleaseArtifacts.loadModuleArtifacts(DetectReleaseArtifacts.java:111)
	at com.itemis.maven.plugins.unleash.steps.actions.DetectReleaseArtifacts.execute(DetectReleaseArtifacts.java:64)
```

**Comment by shillner** [comment]
Hi, I'm not sure if I understand you correctly but I guess you are talking about multiple issues:

1. possibly wrong commit hashes in the metadata.
2. `detectReleaseArtifacts` not working properly if you're skipping `buildReleaseArtifacts`.

- I guess I'll have to check the metadata regarding the commits then.
- The problem with the second issue is that the step `detectReleaseArtifacts` isn't foreseen to be used without `addSpyPlugin` and `buildReleaseArtifacts` at all. This is expected behavior since the spy stuff hasn't been produced. You could argue that it could silently skip its execution in that case, sure, but it is currently expected to fail if no data is available.

**Comment by shillner** [comment]
Btw. I hope I got some time this or next week for maintenance. So I'll check the metadata then.

**Comment by alevinetx** [comment]
Sorry, I was in mid-process of too many things and did not provide enough information.
Points of confusion:

1. In the Jenkins log, the git revision IDs seem to be reported incorrectly with the text:
```
Stored SCM revision before project release: e8fe12f73a136ba5be3cffca124face59eee0da4
....
Git - Commit finished successfully. New revision is: 39bf2bfbc61782ab964ff792900f688aa1d8cfb0
Git - Tag creation finished successfully. New revision is: e8fe12f73a136ba5be3cffca124face59eee0da4
...
Git - Update finished successfully. New revision is: 3ef1f1d307a8188954715660dd831a25506ed6b0
```
The 2nd "new revision" listed is the same ID as the original version checked out.

e8fe is my incoming 1.0.0-SNAPSHOT -- listed as both the incoming and the post-tag version
39bf is the commit and TAG location for 1.0.0 -- This doesn't match the above logged info
3ef1 is the commit for 1.0.1-SNAPSHOT


2. The releaseMetadata.properties:
scm.rev.afterTag=e8fe -- This version (e8fe) is the original revision (1.0.0-SNAPSHOT) that was checked out at the start, rather than (39bf) the TAG commit ID


If these mismatches are due to my alteration of the workflow, then I apologize and I'll change my flow (I can just have the build be as simple as "validate" as the goal, unless that will cause issues, too.

Thank you again !
