### ISSUE TITLE
releaseArgs -Dproperty instead of -Dproperty=true gives NPE

### ISSUE THREAD

**Issue by andreasaronsson** [shillner/unleash-maven-plugin#109]
`
Caused by: java.lang.NullPointerException
	at com.itemis.maven.plugins.unleash.AbstractUnleashMojo.getReleaseArgs(AbstractUnleashMojo.java:263)
`
One option could be to simply put a nullcheck before the log statement and log that the property has no value instead. That could have other consequences that needs to be handled. 
A common use case I see is when I want to mark a build as a release build on the command line. It is more convenient to write -Drelease instead of -Drelease=true. For a varable that is treated as a boolean it is enough to check for existence in other cases it is false. Also the maven profiles match on existence of properties rather than checking if they are set to true or false.

**Comment by andreasaronsson** [comment]
Using `mvn -Dunleash.releaseArgs="-X" unleash:perform` also gives NPE. 
Same thing with `mvn -Dunleash.releaseArgs="X" unleash:perform`
Perhaps I completely misunderstand how to use the argument.

**Comment by andreasaronsson** [comment]
I finally got it to work
`mvn -B -Dunleash.releaseArgs="property=value" unleash:perform`
It would still be nice to know how to be able to pass in "-X" to the release build and to be able to use -Dproperty instead of -Dproperty=value.

**Comment by shillner** [comment]
Will be fixed in 2.9.3 which should be on central today.
You can now pass boolean parameters without the value (if they are set to true) and -e, --errors, -X, --debug through that parameter.

**Comment by andreasaronsson** [comment]
Thanks!
