### ISSUE TITLE
Create a maintenance branch feature

### ISSUE THREAD

**Issue by hmdebenque** [shillner/unleash-maven-plugin#110]
I have been using the unleash plugin  recently for our project release integration and I appreciate a lot the improvement from the maven release plugin. Particularly for the failsafe features and the clean integration with jenkins credentials management.

The drawback is you lose some nice features from the official maven plugin as  the release branch: http://maven.apache.org/maven-release/maven-release-plugin/examples/branch.html

Would it be possible to add this feature ?

Also, implementing all the official release plugin feature would be a nice project.

Thanks for the great work

**Comment by shillner** [comment]
Hi, sorry but I missed that one.

Yes, that would definately be nice but isn't possible at the moment. I'm always open for contributions (PRs) but there's currently no time to implement such stuff, sorry.

But this doesn't mean that those features won't get in in future. There's a good chance that I'll need the release branch feature for an upcoming project by myself ;)

I'll let this issue open as a feature request.
