### ISSUE TITLE
CI Friendly Verisons support

### ISSUE THREAD

**Issue by rbdiang** [shillner/unleash-maven-plugin#116]
Hi I came across this plugin because I was frustrated with the maven-release-plugin and all of its side-effects.  This plugin worked great!   Used in conjunction with the Jenkins Unleash Plugin it save me from needing an additional Jenkins job to perform a release.  Great job.

Does it support [Maven CI Friendly Versions](https://maven.apache.org/maven-ci-friendly.html)?  

The maven-release-plugin does not properly support revisions.  It ignores them, and hard codes the next developmentVersion in all the child module poms.

**Comment by shillner** [comment]
Hi, nice to hear, thanks a lot.
These versions are currently not supported but the change seems to be not so big. You could actually do it on your own by implementing a custom workflow step which replaces the version calculation step. That's what the workflow overriding is for :)
I'll keep this in mind, thanks for the hint.

**Comment by Opa-** [comment]
> These versions are currently not supported

Hi @shillner. Thanks for your plugin. What do you mean by not supported ?
I think this would be a nice addition to the plugin too

**Comment by shillner** [comment]
Hi, sorry but I think this is currently not possible since the plug-in patches the version directly within the pom.

I'll keep this in mind but will have to set up the whole CI,... of the project as this was bound to my old company.

I think the next days I'll update the repo to inform the users about the current state before taking further actions.

**Comment by Opa-** [comment]
Yeah I checked the code after putting my comment and it seems to require more work than I originally though. _Also while looking at the code I noticed that this plugin is released using `maven-release-plugin`, funny 😄_

Thanks for your reply, will look forward to your announcement before taking the decision to use it within my company.

**Comment by shillner** [comment]
Understand that but you can also prepare a PR in the meanwhile ;)

I'll try to migrate the setup the next days and make a plan how things will go on.
