### ISSUE TITLE
Absolut path for released Artifacts

### ISSUE THREAD

**Issue by haunert-msg** [shillner/unleash-maven-plugin#117]
Hi there,
I use a different folder structure for my project. The folders are flat listed instead of nested. Maybe this causes the error "Could not determine project release artifacts.". After debugging the class DetectReleaseArtifacts, I found out what's the problem:
The statement
`String relativePath = props.getProperty(name);`
results in a absolut path for the child maven modules. The statement 
`File artifactFile = new File(p.getBasedir(), relativePath);`
appends this absolut path to the absolut base dir then.
Maybe you can add a check new File(relativePath).isAbsolut() and skip this path concatenation in this case?

Greez,
haunert

**Comment by shillner** [comment]
Hi, thanks for the report and sorry for the late answer but I can hardly invest time into this.
If you provide me a simple test project for this issue I can adapt the implementation respectively.
Thanks so far!
