### ISSUE TITLE
How to configure the remote repository?

### ISSUE THREAD

**Issue by ghost** [shillner/unleash-maven-plugin#118]
I am always runnning into a 
``
[ERROR] An exception was caught while processing the workflow step with id 'deployArtifacts'.                                                  java.lang.NullPointerException: remote repository cannot be null
``

**Comment by shillner** [comment]
Hi, does your POM or one of its parents contain the distribution management section?

**Comment by ghost** [comment]
No, it does not.
my test are all in: https://github.com/tihefrequi/tycho-demo/tree/master/itp01


I think i miss understood the `remote repository`. I thought it would deploy my p2-repository to a server via ftp or somthing like that?

**Comment by shillner** [comment]
Ok, if you don't want to deploy to a Maven repository, then you should override the workflow as described in the wiki and disable the deployment step (and probably the installation step too).
You then also have the option to configure an additional step for your deployment via FTP, HTTP or whatever. Note that you will likely need to implement a custom step for this action (also part of the wiki).

**Comment by ghost** [comment]
Thank you
