### ISSUE TITLE
Issue configuring workflow path through POM

### ISSUE THREAD

**Issue by joca-bt** [shillner/unleash-maven-plugin#120]
I'm trying to configure the workflow location through the POM in the following manner, however it always end up using the default workflow.

```
            <plugin>
                <groupId>com.itemis.maven.plugins</groupId>
                <artifactId>unleash-maven-plugin</artifactId>
                <version>${unleash-maven-plugin.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>com.itemis.maven.plugins</groupId>
                        <artifactId>unleash-scm-provider-git</artifactId>
                        <version>${unleash-scm-provider-git.version}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <workflow>config/maven/unleash-workflow</workflow>
                </configuration>
            </plugin>
```

I've also tried like this:

```
            <plugin>
                <groupId>com.itemis.maven.plugins</groupId>
                <artifactId>unleash-maven-plugin</artifactId>
                <version>${unleash-maven-plugin.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>com.itemis.maven.plugins</groupId>
                        <artifactId>unleash-scm-provider-git</artifactId>
                        <version>${unleash-scm-provider-git.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <phase>unleash</phase>
                        <goals>
                            <goal>perform</goal>
                        </goals>
                        <configuration>
                            <workflow>config/maven/unleash-workflow</workflow>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

`mvn unleash:perform -Dworkflow=config/maven/unleash-workflow` works fine but I really want this specific through the POM.

**Comment by shillner** [comment]
Hi, I've never tried to configure this parameter directly in the plugin settings.
Can you try to use <workflowDescriptor>config/maven/unleash-workflow</workflowDescriptor>?

**Comment by joca-bt** [comment]
I didn't understand, what do you mean by

>  Can you try to use config/maven/unleash-workflow?

It works when specifying the path through the command line if that is what you meant.

I tried configuring through the POM because the wiki mentions it https://github.com/shillner/maven-cdi-plugin-utils/wiki/The-Workflow-Format#default-workflows-and-workflow-overriding.

**Comment by shillner** [comment]
oh sorry, the tag has been stripped in the text.
I mean use `<workflowDescriptor>config/maven/unleash-workflow</workflowDescriptor>` instead of `<workflow>config/maven/unleash-workflow</workflow>`

**Comment by joca-bt** [comment]
It worked. Thanks!
Great plugin by the way!

**Comment by shillner** [comment]
Cool, I'll adapt the wiki page.
Thanks for using the plugin!
