### ISSUE TITLE
Do not change xml and project elements

### ISSUE THREAD

**Issue by joca-bt** [shillner/unleash-maven-plugin#121]
Some of the steps like `setReleaseVersions` change the POM. I noticed they are changing the `<?xml>` and `<project>` elements. Would it be possible to not change those elements?

For example:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
```

is being changed to:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0                              http://maven.apache.org/xsd/maven-4.0.0.xsd">
```

**Comment by shillner** [comment]
I know, yes.
These changes are automatically done by the serializer. I guess there was a proposal once to change this behavior.
I'll keep it in mind for future changes and will see how difficult this fix is.
Thanks for reporting!

**Comment by andreasaronsson** [comment]
I have used
https://maven.apache.org/ref/3.6.2/apidocs/org/apache/maven/model/io/ModelReader.html
and https://maven.apache.org/ref/3.6.2/apidocs/org/apache/maven/model/io/ModelWriter.html
I think they keep the pom as is. https://github.com/andreasaronsson/nextversion-maven-plugin/blob/master/src/main/java/nu/aron/nextbuildnumber/NextBuildNumberLifecycleParticipant.java
But maybe there are other advantages to working with the DOM that does not make it a good idea to use those apis?
