### ISSUE TITLE
SCM credentials via env

### ISSUE THREAD

**Issue by shillner** [shillner/unleash-maven-plugin#22]
Add an option to set the name of environment variables for SCM username and password. Also investigate on certificates and system keystores, ...

**Comment by shillner** [comment]
also support PK passphrase via env

**Comment by shillner** [comment]
maybe use existing parameters and support something like @{env.username}
is ${env.username} already resolved by maven?

**Comment by jgangemi** [comment]
there is a specific maven property for that. i'm using it somewhere, let me find it...

**Comment by jgangemi** [comment]
`${user.name}`

**Comment by shillner** [comment]
${user.name} refers to the name of the current OS user. I think this wouldn't be the right one for SCM access. Also there must be env variables for password and ssh passphrase available. I'm currently thinking about these ones and further options ;)

**Comment by jgangemi** [comment]
you asked if maven resolved `${env.username}` - it does as `${user.name}` :) 

wouldn't these be one and the same 99% of the time? for the others you could probably override `${user.name}` w/ a `-D`

**Comment by shillner** [comment]
No, you misunderstood. I didn't ask that, it was just a reminder for myself to try out different options for setting the username and password by just referring to an env variable. Sure, you can use the user.name variable if this one matches ;) Montag, 22 August 2016, 03:45nachm. +02:00 von Jae Gangemi  notifications@github.com :
