### ISSUE TITLE
Goal for updating versions only

### ISSUE THREAD

**Issue by shillner** [shillner/unleash-maven-plugin#28]
Provide a further goal to only update the versions to release versions! Should simply be re-orchestration of existing steps!

**Comment by jgangemi** [comment]
depending on what you ultimately want to do here, the `versions` plugin already offers something like this.

**Comment by shillner** [comment]
I know, it was an idea to prepare the release versions using the automatic version calculation instead of using the versions plugin where you have to specify the version manually. But its not clear whether it's worth implementing this one.

**Comment by shillner** [comment]
won't be implemented. use maven-versions-pluging.
Would be something like unleash:prepare but is not necessary
