### ISSUE TITLE
Support for Sonatype Nexus

### ISSUE THREAD

**Issue by kasunbg** [shillner/unleash-maven-plugin#37]
Hi,

We are evaluating a couple of Jenkins plugins to automate the release process. Can you let me know whether this plugin support Sonatype Nexus as in M2 Release Plugin?

**Comment by shillner** [comment]
What exactly do you mean by Nexus support?

Nexus is supported as an Aether backend but that is nothing special to Nexus. If you configure your nexus repo as the distribution repository the plugin will upload the artifacts to this repo.

If you mean the staging features of Nexus then no, not yet.

**Comment by kasunbg** [comment]
Yes, I meant the staging features. I should have been more specific. May be it is not in your priority list, but I'd like to see the ability to 'close' a Nexus staging repo once the deployment is done.

Thanks.

**Comment by shillner** [comment]
Ok I will take it onto the feature list but exactly this is the point where this hook-stuff comes into play. Anyone can create custom processing hooks which can then be integrated into the processing workflow. Interested in implementing this one?

**Comment by kasunbg** [comment]
Thanks Shillner. I didn't come across the "hook-stuff" part yet. :-) I will give it a try and see how it goes. I need to figure out the what we are discussing at #38 first.

Thanks.
