### ISSUE TITLE
Run the unleash:perform without any configuration

### ISSUE THREAD

**Issue by kasunbg** [shillner/unleash-maven-plugin#38]
Hi,

Kudos on the great work you are doing, and the awesome docs! Can I know whether it is possible to run the unleash:perform without adding the plugin configuration into the pom.xml?

I'm trying to push for a automated release via Jenkins. But, first I need to show how it works. So, I'd appreciate if this is possible. Only issue could be the need to specify the scm provider as a dependency to the unleash plugin. I'm a bit confused about the step 3 of [Usage](https://github.com/shillner/unleash-maven-plugin/wiki/Usage).

I'm testing it out right now. But thought to reach out and let you know that I'm trying to use your project, and get your feedback as well if possible.

**Comment by shillner** [comment]
Thanks for your appreciation. Cool that you consider this plugin in that early state ;)

Step 3 is required because the plugin itself comes without any concrete SCM provider implementation. I decided to implement this in that way to be more flexible when it comes to the point where more SCM types shall be supported or bug fixes become necessary. Then I can release the API implementations standalone or even others can implement providers for different SCMs and provide them to the community. Sure that implies the need for adding the plugin to the plugin management of the POM but you could also add this plugin to any of the super POMs of your project. I've personally added it to the org-parent of a customer. This is always the parent at the top of the inheritance chain so it will be implicitly available for all projects there.

Why exactly is this config a problem for you?

**Comment by kasunbg** [comment]
@shillner it is not a really a problem. I'm just comparing the maven-release-plugin with yours to get a sense of the advantages yours have. It seems that `mvn release:prepare` can run without any configurations. By configuration, I meant I do not have to mention the plugin in the poms.

I'm doing the CI integration, and is trying to move away from M2 release plugin since you claim to provide better rollback support. I would like to go through this phase without any config changes in the poms.   

Thanks again.

**Comment by kasunbg** [comment]
I ran the following command without any change to poms, and it showed me the following error. 
`mvn com.itemis.maven.plugins:unleash-maven-plugin:1.0.0:perform`

I thought the pom changes are a must. Then, I added the unleash plugin, but that resulted in the same error.  The pom is here - https://github.com/kasunbg/test/blob/unleash-plugin-test/pom.xml#L1192
Would you mind having a look? Thanks.

Can't set level for java.util.logging.ConsoleHandler
Aug 22, 2016 7:32:46 PM org.sonatype.guice.bean.reflect.Logs$JULSink warn
WARNING: Error injecting: com.itemis.maven.plugins.unleash.UnleashMojo
com.google.inject.ProvisionException: Guice provision errors:

1) No implementation for org.eclipse.aether.impl.ArtifactResolver was bound.
  while locating com.itemis.maven.plugins.unleash.UnleashMojo

1 error
    at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:974)
    at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1000)
    at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
    at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:84)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:52)
    at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
    at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:138)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:108)
    at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
    at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
    at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:965)
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1011)
    at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:961)
    at com.google.inject.Scopes$1$1.get(Scopes.java:59)
    at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
    at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
    at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:253)
    at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:245)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:455)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Deployment ........... FAILURE [55.217s]
[INFO] Extras .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 59.331s
[INFO] Finished at: Mon Aug 22 19:32:46 IST 2016
[INFO] Final Memory: 11M/308M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.itemis.maven.plugins:unleash-maven-plugin:1.0.0:perform (default-cli) on project deployment: Execution default-cli of goal com.itemis.maven.plugins:unleash-maven-plugin:1.0.0:perform failed: Unable to load the mojo 'perform' (or one of its required components) from the plugin 'com.itemis.maven.plugins:unleash-maven-plugin:1.0.0': com.google.inject.ProvisionException: Guice provision errors:
[ERROR]
[ERROR] 1) No implementation for org.eclipse.aether.impl.ArtifactResolver was bound.
[ERROR] while locating com.itemis.maven.plugins.unleash.UnleashMojo
[ERROR] at ClassRealm[plugin>com.itemis.maven.plugins:unleash-maven-plugin:1.0.0, parent: sun.misc.Launcher$AppClassLoader@135fbaa4]
[ERROR] while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=com.itemis.maven.plugins:unleash-maven-plugin:1.0.0:perform)
[ERROR]
[ERROR] 1 error
[ERROR] role: org.apache.maven.plugin.Mojo
[ERROR] roleHint: com.itemis.maven.plugins:unleash-maven-plugin:1.0.0:perform
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by shillner** [comment]
1. Yes the release plugin can be used without any config since it is included by default through the plugin group `org.apache.maven.plugins`. This would also be possible if you added `com.itemis.maven.plugins` to the plugin groups in your settings but unfortunately then you are missing the SCM providers. So at the moment you will have to add it to the POM.
2. I can't reproduce this error. If I run `mvn unleash:perform` on your project it starts the release build as expected. Can you update the plugin and scm provider versions to 2.0.0 and try again? Strange thing is that the error is caused by Guice which shouldn't be in the game here.

**Comment by kasunbg** [comment]
Hmm.. I tested this in a docker instance, and I couldn't re-produce this either. I'm checking why.

**Comment by kasunbg** [comment]
In Mac, I keep getting hit with the above error. I have updated the scm git provider version. Here are the environment details. 

Apache Maven 3.0.5
Maven home: /usr/local/Cellar/maven30/3.0.5/libexec
Java version: 1.8.0_xx, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_xx.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.1", arch: "x86_64", family: "mac"

**Comment by jgangemi** [comment]
you're better off adding an entry for the plugin to the`dependencyManagement` section, either in a parent pom or in the project pom itself. adding it to `settings.xml` isn't really portable.

don't forget to check out the associated jenkins plugin for this as well. i'm going to be investigating adding a post build step that allows the unleash plugin to be called after a successful `SNAPSHOT` build once i'm back from vacation next week.

**Comment by jgangemi** [comment]
i think your maven version is incorrect. according to the pom, it wants at least `3.2.1` and you're running `3.0.5`.

**Comment by kasunbg** [comment]
@jgangemi 

> you're better off adding an entry for the plugin to thedependencyManagement section, either in a parent pom or in the project pom itself. adding it to settings.xml isn't really portable.

Did you mean the `pluginManagement` section? As I see, we cannot define the plugins via the settings.xml, we can only define the plugin group. I would love to prove myself wrong though!

And, we are going to use this with Jenkins. That's why the proper recovery mechanisms are important.

> i think your maven version is incorrect. according to the pom, it wants at least 3.2.1 and you're running 3.0.5.

Can you let me know how you came to that conclusion please? I've been running on Maven 3.0.5 without an issue. We've done multiple releases as well with maven-release-plugin before.

Thanks.

**Comment by jgangemi** [comment]
yeah, `pluginManagement` section, sorry and to my knowledge, the pom is the only place you can define it.

i based my maven requirement on this entry in the plugin pom: `<version.maven>3.2.1</version.maven>`. you said you're getting an error trying to run the `unleash` plugin right?

**Comment by kasunbg** [comment]
OK, thanks. good to know. That's why the Docker builds were successful. I had Maven 3.3.9 in there.

**Comment by kasunbg** [comment]
Stumbled upon the following under docker. The environment details are at the end. 

https://repo.maven.apache.org/maven2/net/java/dev/jna/jna-platform/4.1.0/jna-platform-4.1.0.jar (1431 KB at 194.9 KB/sec)
[INFO] WELD-000900: 2.3.3 (Final)
[INFO] WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
[WARNING] WELD-001552: An extension (class com.itemis.maven.plugins.unleash.UnleashMojo) has a non-static public field (public org.eclipse.aether.impl.ArtifactResolver com.itemis.maven.plugins.cdi.AbstractCDIMojo._resolver).
[WARNING] WELD-001552: An extension (class com.itemis.maven.plugins.unleash.UnleashMojo) has a non-static public field (public org.apache.maven.settings.Settings com.itemis.maven.plugins.cdi.AbstractCDIMojo._settings).
[WARNING] WELD-001552: An extension (class com.itemis.maven.plugins.unleash.UnleashMojo) has a non-static public field (public org.eclipse.aether.RepositorySystemSession com.itemis.maven.plugins.cdi.AbstractCDIMojo._repoSystemSession).
[WARNING] WELD-001552: An extension (class com.itemis.maven.plugins.unleash.UnleashMojo) has a non-static public field (public java.util.List com.itemis.maven.plugins.cdi.AbstractCDIMojo._pluginRepos).
[WARNING] WELD-001552: An extension (class com.itemis.maven.plugins.unleash.UnleashMojo) has a non-static public field (public java.io.File com.itemis.maven.plugins.cdi.AbstractCDIMojo.workflowDescriptor).
[WARNING] WELD-001552: An extension (class com.itemis.maven.plugins.unleash.UnleashMojo) has a non-static public field (public boolean com.itemis.maven.plugins.cdi.AbstractCDIMojo.enableLogTimestamps).
[INFO] WELD-000119: Not generating any bean definitions from com.itemis.maven.plugins.unleash.scm.providers.GitSshSessionFactory because of underlying class loading error: Type com.itemis.maven.plugins.unleash.scm.ScmProviderInitialization not found.  If this is unexpected, enable DEBUG logging to see the full error.
[INFO] WELD-000119: Not generating any bean definitions from com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit because of underlying class loading error: Type com.itemis.maven.plugins.unleash.scm.requests.HistoryRequest not found.  If this is unexpected, enable DEBUG logging to see the full error.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Deployment Aggregator Pom ............ FAILURE [ 19.980 s]
[INFO] Extras ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20.854 s
[INFO] Finished at: 2016-08-23T19:58:15+00:00
[INFO] Final Memory: 24M/153M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.itemis.maven.plugins:unleash-maven-plugin:1.0.0:perform (default-cli) on project deployment: Execution default-cli of goal com.itemis.maven.plugins:unleash-maven-plugin:1.0.0:perform failed: com/itemis/maven/plugins/unleash/scm/requests/HistoryRequest: com.itemis.maven.plugins.unleash.scm.requests.HistoryRequest -> [Help 1]

Environment:
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /usr/share/maven
Java version: 1.8.0_102, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.4.15-moby", arch: "amd64", family: "unix"

settings.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
<server>
   <id>nexus-releases</id>
   <username>xxx</username>
   <password>xxx</password>
</server>
</servers>
  <pluginGroups>
    <pluginGroup>org.sonatype.plugins</pluginGroup>
  </pluginGroups>
</settings>
```

**Comment by shillner** [comment]
Hi, I will see whether I can downgrade Maven but I currently don't know exactly what caused this requirement. I'll create an issue for that.
But that's a good point for the docs. I thinks it's not included there.

**Comment by shillner** [comment]
@kasunbg please run this again with plugin version 2.0.0 and git provider version 2.0.0
This error indicates that the Git provider implements another API version than provided by the used plugin.
I will update the error message so that anyone can see the error cause.
I will also create some docs for the providers which include compatible plugin versions.
