### ISSUE TITLE
Dependency check fails on multi-module dependencies (type)

### ISSUE THREAD

**Issue by shillner** [shillner/unleash-maven-plugin#44]
The dependency check fails if a module of a multi-module project references another module of the same project using the version property ${project.version}. Those dependencies should be filtered out during the checks since these properties will be replaced by the release version later.

This failure is caused by a wrong comparison which includes the type of the dependency. Issue #35 handled a similar case where the classifier was the cause.

**Comment by old-o** [comment]
I am still getting "There are SNAPSHOT dependency references!" for inter-module dependencies in this multi-module project: https://github.com/guppy4j/libraries

I am using unleash-maven-plugin 2.6.0 on Jenkins.

**Comment by old-o** [comment]
Correction: I found the problem: I had an entry for an old, no longer existent module in the dependency management section of my parent pom. None of my current modules actually depend on it, but it still threw off the dependenciesCheck step. So I guess my issue was an edge case where an old dependency management still points to a deleted module, that consequentially is not in the reactor list of the build and therefore not removed by filterMultiModuleDependencies(..).
