### ISSUE TITLE
Plugins of Phases install & deploy not executed

### ISSUE THREAD

**Issue by shillner** [shillner/unleash-maven-plugin#50]
Plugin executions that are configured for the phases install and deploy are not executed since these phases are not called during the release.

Possible solutions:
- parse config and execute plugins standalone (difficult, error-prone, ...)
- add note to documentation that those plugins are not executed and must be run previously or as additional steps configured as workflow hooks
- nexus staging can also be implemented as a hook or maybe in the plugin itself but disabled by default.

**Comment by shillner** [comment]
Not really a bug since these phases are ignored by design. Nevertheless, there must be some support for this in future => Nexus staging repo support is already in work.

**Comment by chrisolivier** [comment]
Can you provide an example which show how to run those phases as additional steps configured as workflow hooks ?
I've some difficulty to understand your comment 'Not really a bug since these phases are ignored by design' can you develop that topic ?
Thanks in advance

**Comment by shillner** [comment]
Hi, I meant that it isn't possible to run the phases but it isn't really a bug though since the whole plugin is designed to skip the intallation and deployment phases as these steps are postponed until the very end of the ececution. But unfortunately there it is not possible to simply execute these phases.

So there must be another mechanism to parse and execute plugins bound to these phases, but I didn't find a satisfying solution when I checked of approaches.
