### ISSUE TITLE
API incompatibility error

### ISSUE THREAD

**Issue by shillner** [shillner/unleash-maven-plugin#58]
# Moved issue from [JENKINS-41549](https://issues.jenkins-ci.org/browse/JENKINS-41549)

## Jenkins issue description

Created a simple maven project, ticked Unleash, left the defaults as is, triggered the plugin, left the defaults as is:

[ERROR] Failed to execute goal com.itemis.maven.plugins:unleash-maven-plugin:2.2.3:perform (default-cli) on project promotion-parent: Execution default-cli of goal com.itemis.maven.plugins:unleash-maven-plugin:2.2.3:perform failed: An API incompatibility was encountered while executing com.itemis.maven.plugins:unleash-maven-plugin:2.2.3:perform: java.lang.LinkageError: loader constraint violation: when resolving overridden method "org.jboss.weld.AbstractCDI.select(Ljavax/enterprise/util/TypeLiteral;[Ljava/lang/annotation/Annotation;)Ljavax/enterprise/inject/Instance;" the class loader (instance of org/codehaus/plexus/classworlds/realm/ClassRealm) of the current class, org/jboss/weld/AbstractCDI, and its superclass loader (instance of org/codehaus/plexus/classworlds/realm/ClassRealm), have different Class objects for the type /annotation/Annotation;)Ljavax/enterprise/inject/Instance; used in the signature
[ERROR] -----------------------------------------------------
[ERROR] realm = plugin>com.itemis.maven.plugins:unleash-maven-plugin:2.2.3
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/jenkins/.m2/repository/com/itemis/maven/plugins/unleash-maven-plugin/2.2.3/unleash-maven-plugin-2.2.3.jar
[ERROR] urls[1] = file:/home/jenkins/.m2/repository/com/itemis/maven/plugins/unleash-scm-provider-git/2.0.2/unleash-scm-provider-git-2.0.2.jar

## Environment

- Jenkins 1.630
- Jenkins unleash plugin 2.1.1
- Plugin version: 2.2.3
- SCM provider: Git (2.0.2)

**Comment by alevinetx** [comment]
Everything works fine locally. I was able to successfully promote several times in a row.  So I'm not sure it's the maven plugin.   

I checked my changes back in to git, and tried to launch again.  The same issue with API incompatibility.
As a side note, should this plugin be run as a 2nd step in a job, so that the current pom with an updated pom version is present?  Right now,  my pom is at 004S, but the Jenkins plugin doesn't seem to have a refresh option, so it's only seeing 001S.   If I'm driving this plugin incorrectly, please let me know.   

thanks.

**Comment by shillner** [comment]
Sorry but I don't know what you mean with 001S and 004S.
To run the plug-in correctly you simply have to configure your maven build job, then configure unleash.
For the job you now have the options to either run the "normal" maven build or to run the unleash release build. What do you mean by running as a second step? 

Can you post more details about the Jenkins setup? Jdk, maven installation, job setup. Thanks so far.

**Comment by alevinetx** [comment]
Sorry, I was abbreviating 0.0.1-SNAPSHOT as 001S

So, here's how I got from A to Z:

- I ran the maven plugin (clean unleash:perform) several times locally, which took my poms from 001S to 004S.  
- Git was properly tagged each time.  
- Artifacts were not pushed to artifactory.
- I pushed my updated, and working, pom to git.  Pom is sitting at 004S at this point.
- I went to Jenkins and ran "Trigger Unleash Maven Plugin"
- It took me to the run time configuration screen.
- My modules were sitting at 001S.
- Ran "schedule maven release build"
- Received the API incompatibility error

subsequent launches show that the workspace was pulled from git, and the versions were correct in releasing 004 and adding dev 005S.

subsequent launches produced the API incompatibility error.

So, what I've come to understand:
- The jenkins job should be done after a job that updates the workspace with the latest copy from source.  This will resolve the issue of showing 001S when the source is really 004S.
- The job should be followed by a mvn deploy to push to artifactory.

Question:    Is there any way to run this without intervention?  Tell it to just automatically calculate the next version?

Set up:
Jenkins 1.630
Job:
-  Maven project
- Discard old builds
- JDK default (Oracle 1.8)
- Git repo ssh
 - Clean before checkout
 - wipe out repo and force clone
- Unleash checked
  -- selected repo SCM credentials
 -- everything else left as default

No pre steps
Build:
    Maven 3.2.1
    No goals/options

No post steps.
No post build actions

I hope that helps!!   Thank you for looking in to this.

**Comment by shillner** [comment]
It's a bit confusing because you say your job is configured to clone and checkout the repo before each run. In this case it should not be possible to run on 0.0.1-SNAPSHOT since your remote repo already contains 0.0.4-SNAPSHOT. But yes this is generally the way to go. Configure your job to checkout the latest remote changes (I prefer cleaning the whole workspace before cloning and checking out) and each Maven build (unleash too) works on the latest sources. You also don't need a post step that pushes artifacts to artifactory since unleash performs this task as its very last step.

Nevertheless, the strange thing is that you still run into this API error that I currently have no idea of.
You were talking about a successful build for 0.0.4-SNAPSHOT on Jenkins, is that right? Can you configure your job to update or checkout your sources properly before tha actual buils starts to see if that works. Thanks

**Comment by shillner** [comment]
Hi, I assume you are using a higher Maven version (higher than 3.2.1) locally?!
I ran some tests with older Maven versions and could reproduce the error. When I ran the test with 3.2.1 (the version on your Jenkins) I got the exact same error message. It should work again from version 3.2.2!

Please update the Maven version on your Jenkins CI Server and let me know if this fixed the issue.

**Comment by Hofmaier** [comment]
This error occurs on my local machine too. When I run `mvn com.itemis.maven.plugins:unleash-maven-plugin:2.2.3:perform-tycho` locally with the `unleash-scm-provider-svn` plugin the build process fails.

- Errorlog
[ERROR] Failed to execute goal com.itemis.maven.plugins:unleash-maven-plugin:2.2.3:perform-tycho (default-cli) on project mde: Execution default-cli of goal com.itemis.maven.plugins:unleash-maven-plugin:2.2.3:perform-tycho failed: An API incompatibility was encountered while executing com.itemis.maven.plugins:unleash-maven-plugin:2.2.3:perform-tycho: java.lang.NoSuchMethodError: java.lang.reflect.Method.getParameters()[Ljava/lang/reflect/Parameter;
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.itemis.maven.plugins:unleash-maven-plugin:2.2.3
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy

- Environment
Plugin version: 2.2.4 + 2.2.3
Maven: 3.3.9
JDK: 1.7.0_80
OS. Windows 7

**Comment by shillner** [comment]
Oh, strange.
It's it possible for you to set up a minimal tycho test project for me to test? When I tested it yesterday I was not able to reproduce this behavior.
Maybe there is something wrong in the tycho Mojo. Mittwoch, 01 Februar 2017, 01:07nachm. +01:00 von Lukas Hofmaier  notifications@github.com :

**Comment by alevinetx** [comment]
Okay, yes, the Jenkins job is running using the default 3.2.1.  I've changed it to 3.3.9, which is what I was running on my local machine.  And I'm getting errors.
This is the output with error and debug checked
Rather than pollute this with excessive logs:   http://pastebin.com/aTACs1UM

**Comment by alevinetx** [comment]
Okay, just noticed it's running jdk 17, not 18.  Let me adjust this and cycle back. :/

**Comment by alevinetx** [comment]
finally!! Everything is working.  the only thing i've noticed is that the release was pushed to artifactory when using the Jenkins plugin, but not when just using the maven plugin on a CLI.

So, thank you for listening and helping.   The remaining question is if/when/can there be a flag to allow the plugin to run just as a standard maven job, without using the Launch link, and have it automatically increment POM versions unattended.   That would be ideal, and we could use the Launch link manually when we want to increment a major number,

 Thank you !

**Comment by shillner** [comment]
@Hofmaier: After the latest posts from @alevinetx I think the key to this issue is the Java version. Actually it should run on JDK 1.6 but it may also be that some incompatibilities came in during development since I didn't test on a real 1.6 JDK but developed and ran the tests on 1.8 with source and target compatibility level set to 1.6. Could you try to run your project on 1.8? I will also investigate on this and will either try to fix the incompatibilities or update the requirements to 1.8 if was too much work.

@alevinetx: Actually you are already able to run unleash as a standard Maven job. You simply have to adapt the goals and options of your job configuration to call the unleash plugin directly. Then it would run each time the Maven build job runs and it would automatically upgrade the versions to the next release version (1.1.0-SNAPSHOT -> 1.1.0) and set the next snapshot versions (1.1.0 -> 1.1.1-SNAPSHOT) during the builds. If you then also enable the unleash build wrapper you can also trigger a release manually and set your desired release version.
Hope this helped and fits your needs ;)

**Comment by alevinetx** [comment]
@shillner I just tried it, and indeed, it ran without intervention on my part!  Perhaps you could update the documentation a bit to reflect that information.   

As to @Hofmaier and which jdk, somewhere an API is being called that's only present since 1,.8, FYI, specifically java/util/function/Supplier

Thank you so much for an amazing plugin.  Overcoming the fragility of the standard release, bypassing a 2phase run and broken rollbacks, is impressive and well appreciated.  And, your time to response and willingness to help speaks volumes. Cheers!

**Comment by Hofmaier** [comment]
Thanks for the support. I will try it with JDK 1.8 and let you know if it works or not.

**Comment by shillner** [comment]
Hi, I fixed this issue by replacing incompatible API calls now.
Unfortunately it is no longer possible to run the plugin under JDK 1.6 since the CDI implementation (Weld) requires 1.7!
But at least it is now in harmony with the maven requirement again (1.7 for Maven 3.3).
I also tested the plugin with 1.7 and Maven 3.2.1 successfully.

The fix is available as version 2.3.0
