### ISSUE TITLE
Request for indicating which decimal to increment 

### ISSUE THREAD

**Issue by alevinetx** [shillner/unleash-maven-plugin#60]
Right now, as far as I can see, the auto increment works only against the rightmost (3rd?) release number.  Being able to have it increment a minor or major number would be nice to have.   I don't know if anyone uses more than 3 numbers, but I'm thinking using a 1-based index from the right would handle all use cases.  And it would likely default to 1, to continue current behavior without breaking anyone's builds.

-DincrementVersionAt=2    would change Y in X.Y.Z

Thank you for the consideration !

**Comment by alevinetx** [comment]
Just as a reference for anyone working with pom version numbers:
http://books.sonatype.com/mvnref-book/reference/pom-relationships-sect-pom-syntax.html
https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN8855

**Comment by shillner** [comment]
Hi, I'm not quite sure whether it would be so good to introduce such a parameter. But in just for the case I wouldn't set an index but rather take an enum literal identifying the exact part of the version. I thought of something like `MAJOR`, `MINOR`, `INCREMENTAL` and `LOWEST` where lowes is the default which refers to the rightmost part of the version which can be the incremental part or even something like a qualifier, e.g. ALPHA1, ...

I'll try this out

**Comment by vovtz** [comment]
+1

This feature could prevent a lot of Groovy scripting inside Jenkins jobs. Ideally this would also be selectable from the Jenkins plug-in.

**Comment by shillner** [comment]
I've already scheduled this feature for 2.4.0!

**Comment by shillner** [comment]
available in 2.4.0 for goal `perform`.

**Comment by shillner** [comment]
Appropriate support by the jenkins plugin is already implemented and will be released soon. There are currently some problems that need to be fixed.
