### ISSUE TITLE
SCM connection URL isn't correct for sub modules (SVN)

### ISSUE THREAD

**Issue by doctorsmith** [shillner/unleash-maven-plugin#64]
After starting a release on a multi module Maven project the SCM connection and url tag are not the expected ones (sub modules).

Example:
Trunk:
`<scm><connection>scm:svn:svn://.../sample-project/trunk/core</connection></scm>
`
After Release:
`<scm><connection>scm:svn:svn://.../sample-project/tags/1.0.0</connection></scm>
`
The right one should be:
`<scm><connection>scm:svn:svn://.../sample-project/tags/1.0.0/core</connection></scm>
`

**Comment by shillner** [comment]
Moved issue to SVN provider: [https://github.com/shillner/unleash-scm-provider-svn/issues/4](https://github.com/shillner/unleash-scm-provider-svn/issues/4)
