### ISSUE TITLE
Make releasebuild goals configurable

### ISSUE THREAD

**Issue by pfink** [shillner/unleash-maven-plugin#78]
Currently, the releasebuild goals are hard-coded: https://github.com/shillner/unleash-maven-plugin/blob/master/plugin/src/main/java/com/itemis/maven/plugins/unleash/steps/actions/BuildProject.java#L104

Anyway, some plugins require that aritifacts are directly installed during release build, e.g. the maven-karaf-plugin: http://karaf.922171.n3.nabble.com/Karaf-maven-plugin-package-vs-install-td4045769.html

So it would be good to make the releasebuild goals configurable to handle such special cases, even though it would may result in a break of the plugins design. Sometimes it's more important to get things to work ;-)

**Comment by shillner** [comment]
Hi, I'm not sure about the impact of such a change. Making the release goals configurable could lead to weird issues.
What does the karaf-maven-plugin do exactly and why does it need to install the artifacts?

**Comment by shillner** [comment]
Hi, I've provided a first version in a new branch (`configurable-goals`). Could you please check this branch out and see whether this would work for you?
There is a new parameter `goals` with system property `unleash.goals` taking a list. So you should be able to say `-Dunleash.goals=clean,install` when calling the release.

I'm not yet sure about the danger and consequences and think it could be necessary that further restrictions apply if one overrides the release goals. But waiting for your response first.

**Comment by pfink** [comment]
The karaf-maven-plugin takes artifacts from the repository and verifies them. I also opened an issue on the karad plugin to adress the issue: https://issues.apache.org/jira/browse/KARAF-5164?jql=text%20~%20"reactor%20maven%20karaf"

I'll check your branch within the next days, thanks! 👍

**Comment by pfink** [comment]
Sorry for the delay in my response. I had several other issues in my build process that prevented to check whether the full lifecycle still works when `-Dunleash.goals=clean,install` is set. To be honest, I can still not easily check if the deployArtifacts step is still working because of #81.

Anyway, the mentioned issue with the karaf-maven-plugin does not occur anymore when using the version of your feature branch and `-Dunleash.goals=clean,install`. This is a huge step forward 👍 Thanks for implementing this so fast!

(of course, it's clear that transactionality is sort of lost when the local maven repo is not cleared manually afterwards)
