### ISSUE TITLE
Add support for "-DaltDeploymentRepository=..."

### ISSUE THREAD

**Issue by pfink** [shillner/unleash-maven-plugin#81]
When I run `mvn deploy`, I can define an alternative deployment repository by adding the parameter `-DaltDeploymentRepository=...` or `-DaltReleaseDeploymentRepository=...` (documentation can be found [here](http://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html)). This is very important when debugging/testing the release of many artifacts with different release repositories: With the parameter, I can lead them all to a "sandbox" repository without having to modify the pom file of each artifact. This is also useful for Jenkins jobs that should check whether a full release _would_ be possible without doing the actual release, but still checking/executing the full lifecycle.

It would be very helpful if the unleash maven plugin would also support  `-DaltDeploymentRepository=...` or `-DaltReleaseDeploymentRepository=...`.

**Comment by shillner** [comment]
Hi, I don't know if this is ok for you but I guess this should also do the trick.
From my needs in a customer project I introduced a feature to additionally deploy the artifacts to several other repositories. This can now also be configured using system properties.
If you remove the repo definition of the project and specify the repository through one of that properties you should be able to achieve your goal.

Please refer to the [documentation](https://github.com/shillner/unleash-maven-plugin/wiki/unleash%3Aperform#additionaldeploymentrepositories)

**Comment by pfink** [comment]
Mhm, the whole idea of this was not having to modify 20 POMs in the POM hierarchy if you want to do a simple test without affecting the PROD repositories. If you have to modify the POM, nothing is really gained compared to the situation before...

**Comment by shillner** [comment]
Ok, understand. You want to have the deployment repos in your build setup and just override them for testing purpose.
I'll reopen the issue and will implement this feature asap as deployment stuff is currently on the list ;)
