### ISSUE TITLE
Add Mercurial (HG) SCM provider.

### ISSUE THREAD

**Issue by Jorelia** [shillner/unleash-maven-plugin#82]
Could you please, add the Mercurial SCM provider for your plug-in ? We know that there is more tooling for GIT with Jenkins...but we are using Mercurial (work well with the Maven Release Plugin)...and your plug-in is more efficient, flexible and seems more robust. Then, we definitively want an HG SCM provider. Please and thank you very much. Best regards,

**Comment by shillner** [comment]
Hi, sorry but this is far more work than I am currently able to invest.
I'd really appreciate any help of the community. You could start implementing a provider for Mercurial and send some PRs for review if you like.
On the other hand we could offer some small consulting quota for the integration of the tooling into your CI pipeline. If you are interested in one of the options please let me know.
