### ISSUE TITLE
Retain POM format as possible as we can

### ISSUE THREAD

**Issue by tan9** [shillner/unleash-maven-plugin#85]
Current DOM-based POM manipulation may create unwanted change, for example:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
```
will be modified to:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
```

Self-closed elements like `<AlwaysFail />` will be modified to `<AlwaysFail/>`. And the newline at EOF issue opinionated "fixed" in #83...

Since this is the [limitation of DOM](https://stackoverflow.com/a/869439/3440376),  maybe we can adapt StAX just like [what `versions-maven-plugin` did](https://github.com/mojohaus/versions-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/versions/rewriting/ModifiedPomXMLEventReader.java)? Or adapt something like [DecentXML](https://bitbucket.org/digulla/decentxml) which will preserve all format.

**Comment by shillner** [comment]
I know about that issue but it's still too unimportant to invest time on it. It's just a few format changes so I think it doesn't hurt too bad.

**Comment by tan9** [comment]
I think a tool that will break team's code convention is not a good option, unless it brings the benefits outweigh these shortcomings (like **unleash** :smile: ). Another information will be erased by unleash is the legal notices enforced by the firm above the XML prolog.

If there are enough test cases in the code base, I may try to investigate into it for a better user experience.

**Comment by shillner** [comment]
Ok, feel free to build a prototype ;)
I think the adaption of DecentXML seems to be a bit easier than using the StAX approach but I'm open to both of them!
