### ISSUE TITLE
Unleash plugin overwrites <scm> tag in pom.xml

### ISSUE THREAD

**Issue by pfink** [shillner/unleash-maven-plugin#91]
The unleash plugin overwrites the scm tag within the pom.xml. Is there a possibility to prevent this? I intentionally introduced a property for the Git base url so that it's easier to keep everything working on forks (which obviously have a different base url from the original project). But as you can see within the screenshot below, unleash overwrites it with hard-coded base url's...

![image](https://user-images.githubusercontent.com/7902693/30787143-a3753f68-a182-11e7-9bd0-f6151c6d1573.png)

Thanks for your help!

**Comment by shillner** [comment]
Hi, sorry for the late answer but there was no time until now.
I'll consider this as a bug and try to provide a fix with the next release.

**Comment by shillner** [comment]
Hi, the SCM connection strings are now preserved during the process.
