### ISSUE TITLE
allow variable expansion in scm message prefix

### ISSUE THREAD

**Issue by jorgheymans** [shillner/unleash-maven-plugin#95]
it would be nice if the scmCommit message can contain the version that was just released i.e. 'release 0.38' , to make the scm history easy to scan for release points. For this i guess you could apply the same variable expansion mechanism as from the tagNamePattern.

**Comment by jorgheymans** [comment]
a workaround is do this in the pom

```
        <configuration>
          <scmMessagePrefix>[release ${unleash.releaseVersion}]</scmMessagePrefix>
        </configuration>
```

**Comment by shillner** [comment]
Sure, this makes sense and is easy to implement. I'll schedule this for 2.8.0.

**Comment by shillner** [comment]
is already part of 2.8.0
