### ISSUE TITLE
Failure with NoClassDefFoundError

### ISSUE THREAD

**Issue by akravets** [shillner/unleash-maven-plugin#99]
Hi,

When executing perform-tycho goal on my project I am getting error `Execution default-cli of goal com.itemis.maven.plugins:unleash-maven-plugin:2.7.3:perform-tycho failed: java.lang.NoClassDefFoundError: org/eclipse/tycho/model/IU: org.eclipse.tycho.model.IU -> [Help 1]`. Can someone clarify the nature of this error? Am I missing some dependency?

**Comment by shillner** [comment]
Hi, can you please post the stack trace and provide a minimal sample project where the error occurs? There is also version 2.7.4 since yesterday using Tycho 1.0.0. Maybe this already helps.  Mittwoch, 20 Dezember 2017, 00:04vorm. +01:00 von akravets  notifications@github.com :

**Comment by akravets** [comment]
Hi,

Here is minimal example that shows [failure](https://github.com/akravets/tycho-sandbox/tree/master/com.akravets.unleash), and here is the log including [error message](https://github.com/akravets/tycho-sandbox/issues/2). 

Thanks,
Alex

**Comment by shillner** [comment]
Hi Thanks again for the report and the sample project. After a hard search I finally found the error.
Version 2.7.4 uses Tycho in version 1.0.0 which is incompatible with the version you are using (0.22.0). When I upgrade the tycho version of the project to 1.0.0 (at least 0.23.0) everything seems to work.

**Comment by akravets** [comment]
Awesome! Thanks for taking time to look into this.
